version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL="mongodb+srv://Ans2003:a2003ns@ans2003.qp6dlxl.mongodb.net/?retryWrites=true&w=majority"
      - serverPort=5000
    volumes:
      - .:/app
      - /app/node_modules